### ISSUE TITLE
Install Not Working - Echo

### ISSUE THREAD

**Issue by u382514** [olebedev/go-starter-kit#44] opened 2016-04-12 19:39 UTC
Went through install instructions on README on fresh go 1.6 install. On MAKE SERVE it is crashing stating "cannot find pkg github.com/labstack/echo" in "vendor/gopkg.in/labstack/echo.v1/middleware/auth.go:7:2"

Of course if you do a "go get" on that package it crashes with all kinds of error messages. What's the best way to get past this error?

**Comment by u382514** [comment] 2016-04-12 20:24
UPDATE: Changing the srlt.yaml file and running srlt restore for the following pacakges/commit ID's seems to have fixed the issue for me. 

gopkg.in/labstack/echo.v1: f12d77f9cf7a374fa39e2e029a439c55e59dbc91
github.com/labstack/gommon: f8343700e8769e645b5f9949ec2e3a69f9fd71eb

**Comment by olebedev** [comment] 2016-04-13 05:33
Hi @u382514,

thanks for your report. I have just merged #42 PR and it seems the problem is solved. If you still have a problem with it, please let me know.

**Closed by olebedev** 2016-04-13 05:33 UTC
