### ISSUE TITLE
Doesn't work with React 15.0

### ISSUE THREAD

**Issue by valerius257** [olebedev/go-starter-kit#47] opened 2016-05-08 09:24 UTC
After updating React to 15.0 everything compiles successfully but project doesn't start.

![capture](https://cloud.githubusercontent.com/assets/5458823/15097015/61865b76-1517-11e6-8dab-206af7ad3d90.PNG)

**Comment by olebedev** [comment] 2016-05-10 04:55
Thank for the report.  Once I'm fix it I'll ping here.

**Comment by nbjahan** [comment] 2016-05-14 10:12
This is a **React** bug caught by **Ducktape**!
The problem is an invalid escape char in one of the regexes introduced in this commit: https://github.com/facebook/react/commit/a2b471e09850f1546fd2526149fc04992cb85b80

here is the patch: https://github.com/facebook/react/pull/6772

P.S. It would be useful to see the stack trace in this situations [server/react.go#L180](https://github.com/olebedev/go-starter-kit/blob/master/server/react.go#L180)

**Comment by valerius257** [comment] 2016-05-14 18:23
I could confirm that using React from [32c750de5c47436168b742275ebe21852dcca172](https://github.com/facebook/react/commit/32c750de5c47436168b742275ebe21852dcca172) solved the issue

**Comment by abh** [comment] 2016-08-12 07:28
Close this?

**Comment by olebedev** [comment] 2016-08-12 10:00
@abh yup!

**Closed by olebedev** 2016-08-12 10:00 UTC
